FROM php:7-apache

# Add Config
ADD php.ini /usr/local/etc/php/conf.d/
ADD vim/.vimrc /root
ADD git/.gitignore_global /root
ADD ssh /root/.ssh
ADD bootstrap.sh /bootstrap.sh
RUN chmod +x /bootstrap.sh
RUN /bootstrap.sh
