FROM node:8.9.2

RUN apt-get update && apt-get install -y \
    vim \
    nano \
    npm \
    apt-transport-https \
    zsh \
    sudo

# Install Yarn
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN apt-get update && apt-get install -y yarn

RUN npm install -g @angular/cli
RUN npm install -g @vue/cli-service-global
RUN npm install -g create-react-app
RUN npm install -g foundation-cli
RUN npm install -g bootstrap-cli
RUN npm install -g bower

# ENTRYPOINT
ADD node/entrypoint.sh /entrypoint.sh
RUN chmod 777 /entrypoint.sh

# SSh Config
ADD _config/ssh ~/.ssh

# Add some config
ADD _config/vim/.vimrc ~/.vimrc

# Git config
ADD _config/git/.gitignore_global ~/.gitignore_global
RUN git config --global core.excludesfile '~/.gitignore_global'
RUN git config --global push.default simple

# Instal Oh my Zsh
RUN bash -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
RUN sed -i -- 's/robbyrussell/sonicradish/g' ~/.zshrc # Other awesome theme: random kafeitu sonicradish wezm+

