FROM php:8.0.3-fpm

# Install Packages
RUN apt-get update && apt-get install -y \
    vim \
    nano \
    zsh \
    git \
    zlib1g-dev \
    libicu-dev \
    libexif-dev \
    wkhtmltopdf \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libpng-dev \
    httpie \
    sudo \
    librabbitmq-dev \
    libssh-dev \
    libonig-dev \
    libzip-dev

RUN docker-php-ext-configure \
    gd --with-freetype --with-jpeg

RUN docker-php-ext-install \
    pdo \
    pdo_mysql \
    mysqli \
    zip \
    bcmath \
    intl \
    opcache \
    calendar \
    pcntl \
    gd \
    iconv \
    exif \
    bcmath \
    sockets

# Install APCu
RUN pecl install apcu
RUN echo "extension=apcu.so" > /usr/local/etc/php/conf.d/apcu.ini

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php
RUN mv composer.phar /usr/local/bin/composer
ENV COMPOSER_ALLOW_SUPERUSER=1

# PHP Deployer
RUN curl -LO http://deployer.org/deployer.phar
RUN mv deployer.phar /usr/local/bin/dep
RUN chmod +x /usr/local/bin/dep
RUN dep self-update

# PHP CS Fixer
RUN curl -L https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/download/v1.11.6/php-cs-fixer.phar -o php-cs-fixer
RUN chmod a+x php-cs-fixer
RUN mv php-cs-fixer /usr/local/bin/php-cs-fixer

# PHP Unit
RUN curl https://phar.phpunit.de/phpunit.phar -L -o phpunit.phar
RUN chmod +x phpunit.phar
RUN mv phpunit.phar /usr/local/bin/phpunit

# Symfony
RUN curl -sS https://get.symfony.com/cli/installer | bash
RUN mv /root/.symfony/bin/symfony /usr/local/bin/symfony

# ENTRYPOINT
ADD php/entrypoint.sh /entrypoint.sh
RUN chmod 777 /entrypoint.sh

# SSh Config
ADD _config/ssh /root/.ssh

# Right access
RUN usermod -u 1000 www-data

# Add some config
ADD php/config/php.ini /usr/local/etc/php/conf.d/
ADD php/config/www.conf /usr/local/etc/php-fpm.d/
ADD _config/vim/.vimrc /root/.vimrc

# Git config
ADD _config/git/.gitignore_global /root/.gitignore_global
RUN git config --global core.excludesfile '/root/.gitignore_global'
RUN git config --global push.default simple

# Instal Oh my Zsh
RUN bash -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
RUN sed -i -- 's/robbyrussell/wezm+/g' /root/.zshrc # Other awesome theme: random kafeitu sonicradish wezm+
